# Configuration

title: Judy (Zephyr) Fan 
email: hello@judyfan.me
description: >- # this means to ignore newlines until "baseurl:"
    Judy Fan's personal website, hosting a blog and art portfolio.
url: "https://borby.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - portfolio.md

footer: 'follow me on <a href="https://linkedin.com/in/judy-fan">LinkedIn</a>'
google_analytics: UA-196239696-1 
